eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          url: http://localhost:8090
          predicates:
            - Path=/api/student/**
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
