eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka

server:
  port: 8050
spring:
  application:
    name: exceptions
  config:
    import: optional:configserver:http://localhost:8888
